import type { User, Asset, Allocation } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@company.com",
    password: "admin123",
    role: "admin",
    designation: "IT Administrator",
    department: "IT",
    profileImage: "/admin-profile.png",
    employeeId: "ADM001",
  },
  {
    id: "2",
    name: "John Doe",
    email: "john@company.com",
    password: "john123",
    role: "employee",
    designation: "Software Engineer",
    department: "Engineering",
    profileImage: "/employee-profile.jpg",
    employeeId: "EMP001",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@company.com",
    password: "jane123",
    role: "employee",
    designation: "Product Manager",
    department: "Product",
    profileImage: "/employee-profile.jpg",
    employeeId: "EMP002",
  },
]

export const mockAssets: Asset[] = [
  {
    id: "1",
    assetId: "ASSET001",
    name: "Dell Laptop",
    category: "Computers",
    model: "XPS 13",
    configuration: "i7, 16GB RAM, 512GB SSD",
    serialNumber: "SN123456",
    purchaseDate: "2023-01-15",
    warrantyExpiry: "2026-01-15",
    status: "allocated",
    allocatedTo: "EMP001",
    allocationDate: "2023-02-01",
    allocationType: "Permanent",
  },
  {
    id: "2",
    assetId: "ASSET002",
    name: "Apple MacBook",
    category: "Computers",
    model: 'MacBook Pro 14"',
    configuration: "M2, 16GB RAM, 256GB SSD",
    serialNumber: "SN123457",
    purchaseDate: "2023-03-10",
    warrantyExpiry: "2026-03-10",
    status: "allocated",
    allocatedTo: "EMP002",
    allocationDate: "2023-04-01",
    allocationType: "Permanent",
  },
  {
    id: "3",
    assetId: "ASSET003",
    name: "HP Monitor",
    category: "Peripherals",
    model: '27" 4K',
    configuration: "4K, 60Hz",
    serialNumber: "SN123458",
    purchaseDate: "2023-02-20",
    warrantyExpiry: "2025-02-20",
    status: "available",
  },
  {
    id: "4",
    assetId: "ASSET004",
    name: "Logitech Keyboard",
    category: "Peripherals",
    model: "MX Keys",
    configuration: "Wireless",
    serialNumber: "SN123459",
    purchaseDate: "2023-03-05",
    warrantyExpiry: "2025-03-05",
    status: "under_repair",
  },
]

export const mockAllocations: Allocation[] = [
  {
    id: "1",
    assetId: "1",
    employeeId: "EMP001",
    allocationDate: "2023-02-01",
    allocationType: "Permanent",
    remarks: "Development laptop",
    status: "approved",
    acknowledgmentDate: "2023-02-02",
  },
  {
    id: "2",
    assetId: "2",
    employeeId: "EMP002",
    allocationDate: "2023-04-01",
    allocationType: "Permanent",
    remarks: "Design work laptop",
    status: "pending",
  },
]

export const mockEmployees: User[] = [
  {
    id: "2",
    name: "John Doe",
    email: "john@company.com",
    role: "employee",
    designation: "Software Engineer",
    department: "Engineering",
    profileImage: "/diverse-office-employee.png",
    employeeId: "EMP001",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@company.com",
    role: "employee",
    designation: "Product Manager",
    department: "Product",
    profileImage: "/diverse-office-employee.png",
    employeeId: "EMP002",
  },
]
