import type { User, Asset, Allocation } from "./types"

export const mockUsers: User[] = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@company.com",
    password: "admin123",
    role: "admin",
    designation: "IT Administrator",
    department: "IT",
    profileImage: "/admin-profile.png",
    employeeId: "ADM001",
  },
  {
    id: "2",
    name: "John Doe",
    email: "john@company.com",
    password: "john123",
    role: "employee",
    designation: "Software Engineer",
    department: "Engineering",
    profileImage: "/employee-profile.jpg",
    employeeId: "EMP001",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@company.com",
    password: "jane123",
    role: "employee",
    designation: "Product Manager",
    department: "Product",
    profileImage: "/employee-profile.jpg",
    employeeId: "EMP002",
  },
  {
    id: "4",
    name: "Robert Johnson",
    email: "robert@company.com",
    password: "robert123",
    role: "employee",
    designation: "UX Designer",
    department: "Design",
    profileImage: "/employee-profile.jpg",
    employeeId: "EMP003",
  },
  {
    id: "5",
    name: "Sarah Williams",
    email: "sarah@company.com",
    password: "sarah123",
    role: "employee",
    designation: "Data Analyst",
    department: "Analytics",
    profileImage: "/employee-profile.jpg",
    employeeId: "EMP004",
  },
  {
    id: "6",
    name: "Michael Brown",
    email: "michael@company.com",
    password: "michael123",
    role: "employee",
    designation: "DevOps Engineer",
    department: "Operations",
    profileImage: "/employee-profile.jpg",
    employeeId: "EMP005",
  },
]

export const mockAssets: Asset[] = [
  // Laptops (Computers)
  {
    id: "1",
    assetId: "ASSET001",
    name: "Dell Laptop",
    category: "Computers",
    model: "XPS 13",
    configuration: "i7, 16GB RAM, 512GB SSD",
    serialNumber: "DLXPS13-001",
    purchaseDate: "2023-01-15",
    warrantyExpiry: "2026-01-15",
    status: "available",
    allocationType: "Company Owned",
  },
  {
    id: "2",
    assetId: "ASSET002",
    name: "Apple MacBook",
    category: "Computers",
    model: 'MacBook Pro 14"',
    configuration: "M2, 16GB RAM, 256GB SSD",
    serialNumber: "MBP14-001",
    purchaseDate: "2023-03-10",
    warrantyExpiry: "2026-03-10",
    status: "available",
    allocationType: "Company Owned",
  },
  {
    id: "3",
    assetId: "ASSET003",
    name: "Lenovo ThinkPad",
    category: "Computers",
    model: "X1 Carbon",
    configuration: "i5, 8GB RAM, 256GB SSD",
    serialNumber: "LNTKP-001",
    purchaseDate: "2023-05-20",
    warrantyExpiry: "2026-05-20",
    status: "available",
    allocationType: "Employee Owned",
  },
  {
    id: "4",
    assetId: "ASSET004",
    name: "HP EliteBook",
    category: "Computers",
    model: "840 G9",
    configuration: "i7, 32GB RAM, 1TB SSD",
    serialNumber: "HPELB-001",
    purchaseDate: "2023-07-12",
    warrantyExpiry: "2026-07-12",
    status: "available",
    allocationType: "Company Owned",
  },
  
  // Mobile Devices
  {
    id: "5",
    assetId: "ASSET005",
    name: "iPhone",
    category: "Mobile",
    model: "14 Pro",
    configuration: "256GB, Space Black",
    serialNumber: "IPH14-001",
    purchaseDate: "2023-06-01",
    warrantyExpiry: "2025-06-01",
    status: "available",
  },
  {
    id: "6",
    assetId: "ASSET006",
    name: "Samsung Galaxy",
    category: "Mobile",
    model: "S23 Ultra",
    configuration: "512GB, Phantom Black",
    serialNumber: "SGS23-001",
    purchaseDate: "2023-08-15",
    warrantyExpiry: "2025-08-15",
    status: "available",
  },
  {
    id: "7",
    assetId: "ASSET007",
    name: "Google Pixel",
    category: "Mobile",
    model: "7 Pro",
    configuration: "128GB, Snow",
    serialNumber: "GPXL7-001",
    purchaseDate: "2023-09-10",
    warrantyExpiry: "2025-09-10",
    status: "available",
  },
  {
    id: "8",
    assetId: "ASSET008",
    name: "OnePlus",
    category: "Mobile",
    model: "11 5G",
    configuration: "256GB, Titan Black",
    serialNumber: "OP11-001",
    purchaseDate: "2023-10-05",
    warrantyExpiry: "2025-10-05",
    status: "available",
  },
  
  // Monitors
  {
    id: "9",
    assetId: "ASSET009",
    name: "Dell Monitor",
    category: "Monitor",
    model: '27" UltraSharp',
    configuration: "4K, USB-C, Height Adjustable",
    serialNumber: "DLMON-001",
    purchaseDate: "2023-02-20",
    warrantyExpiry: "2026-02-20",
    status: "available",
  },
  {
    id: "10",
    assetId: "ASSET010",
    name: "LG Monitor",
    category: "Monitor",
    model: '34" UltraWide',
    configuration: "3440x1440, 144Hz, Curved",
    serialNumber: "LGMON-001",
    purchaseDate: "2023-04-15",
    warrantyExpiry: "2026-04-15",
    status: "available",
  },
  {
    id: "11",
    assetId: "ASSET011",
    name: "Samsung Monitor",
    category: "Monitor",
    model: '32" Odyssey',
    configuration: "4K, 165Hz, Quantum HDR",
    serialNumber: "SGMON-001",
    purchaseDate: "2023-07-30",
    warrantyExpiry: "2026-07-30",
    status: "available",
  },
  {
    id: "12",
    assetId: "ASSET012",
    name: "ASUS Monitor",
    category: "Monitor",
    model: '24" ProArt',
    configuration: "1080p, Color Accurate",
    serialNumber: "ASMON-001",
    purchaseDate: "2023-11-10",
    warrantyExpiry: "2026-11-10",
    status: "available",
  },
  
  // Accessories
  {
    id: "13",
    assetId: "ASSET013",
    name: "Sony Headphones",
    category: "Headphone",
    model: "WH-1000XM5",
    configuration: "Noise Cancelling, Wireless",
    serialNumber: "SNYHP-001",
    purchaseDate: "2023-03-05",
    warrantyExpiry: "2025-03-05",
    status: "available",
  },
  {
    id: "14",
    assetId: "ASSET014",
    name: "Bose Headphones",
    category: "Headphone",
    model: "QuietComfort 45",
    configuration: "Noise Cancelling, Bluetooth",
    serialNumber: "BOSHP-001",
    purchaseDate: "2023-05-12",
    warrantyExpiry: "2025-05-12",
    status: "available",
  },
  {
    id: "15",
    assetId: "ASSET015",
    name: "Logitech Mouse",
    category: "Mouse",
    model: "MX Master 3S",
    configuration: "Wireless, Ergonomic",
    serialNumber: "LGTMS-001",
    purchaseDate: "2023-04-10",
    warrantyExpiry: "2025-04-10",
    status: "available",
  },
  {
    id: "16",
    assetId: "ASSET016",
    name: "Razer Mouse",
    category: "Mouse",
    model: "DeathAdder V3",
    configuration: "Wired, 30K DPI",
    serialNumber: "RZRMS-001",
    purchaseDate: "2023-06-20",
    warrantyExpiry: "2025-06-20",
    status: "available",
  },
  {
    id: "17",
    assetId: "ASSET017",
    name: "Logitech Keyboard",
    category: "Keyboard",
    model: "MX Keys S",
    configuration: "Wireless, Backlit",
    serialNumber: "LGTKB-001",
    purchaseDate: "2023-03-15",
    warrantyExpiry: "2025-03-15",
    status: "available",
  },
  {
    id: "18",
    assetId: "ASSET018",
    name: "Keychron Keyboard",
    category: "Keyboard",
    model: "K8 Pro",
    configuration: "Mechanical, Wireless",
    serialNumber: "KCHKB-001",
    purchaseDate: "2023-08-05",
    warrantyExpiry: "2025-08-05",
    status: "available",
  },
  {
    id: "19",
    assetId: "ASSET019",
    name: "Dell Dock Station",
    category: "Dock-station",
    model: "WD19TBS",
    configuration: "Thunderbolt 3, 180W",
    serialNumber: "DLDKS-001",
    purchaseDate: "2023-02-25",
    warrantyExpiry: "2026-02-25",
    status: "available",
  },
  {
    id: "20",
    assetId: "ASSET020",
    name: "Caldigit Dock",
    category: "Dock-station",
    model: "TS4",
    configuration: "Thunderbolt 4, 98W",
    serialNumber: "CALDK-001",
    purchaseDate: "2023-09-18",
    warrantyExpiry: "2026-09-18",
    status: "available",
  },
  {
    id: "21",
    assetId: "ASSET021",
    name: "Apple Mac Connector",
    category: "Mac-Connector",
    model: "USB-C to HDMI",
    configuration: "4K @ 60Hz",
    serialNumber: "APLMC-001",
    purchaseDate: "2023-01-30",
    warrantyExpiry: "2026-01-30",
    status: "available",
  },
  {
    id: "22",
    assetId: "ASSET022",
    name: "Anker Mac Connector",
    category: "Mac-Connector",
    model: "7-in-1 Hub",
    configuration: "HDMI, USB, Ethernet",
    serialNumber: "ANKMC-001",
    purchaseDate: "2023-05-25",
    warrantyExpiry: "2026-05-25",
    status: "available",
  },
  
  // Previously allocated assets (for testing)
  {
    id: "23",
    assetId: "ASSET023",
    name: "Dell Laptop",
    category: "Computers",
    model: "Latitude 5430",
    configuration: "i5, 16GB RAM, 512GB SSD",
    serialNumber: "DLLAT-001",
    purchaseDate: "2023-02-01",
    warrantyExpiry: "2026-02-01",
    status: "allocated",
    allocatedTo: "EMP001",
    allocationDate: "2023-02-01",
    allocationType: "Permanent",
  },
  {
    id: "24",
    assetId: "ASSET024",
    name: "HP Monitor",
    category: "Peripherals",
    model: '24" EliteDisplay',
    configuration: "1080p, 75Hz",
    serialNumber: "HPMON-001",
    purchaseDate: "2023-02-20",
    warrantyExpiry: "2025-02-20",
    status: "under_repair",
  },
]

export const mockAllocations: Allocation[] = [
  {
    id: "1",
    assetId: "23",
    employeeId: "EMP001",
    allocationDate: "2023-02-01",
    allocationType: "Permanent",
    remarks: "Development laptop for new project",
    status: "approved",
    acknowledgmentDate: "2023-02-02",
  },
  {
    id: "2",
    assetId: "24",
    employeeId: "EMP002",
    allocationDate: "2023-04-01",
    allocationType: "Temporary",
    remarks: "Temporary monitor while main one is being repaired",
    status: "pending",
  },
  {
    id: "3",
    assetId: "14",
    employeeId: "EMP003",
    allocationDate: "2023-06-15",
    allocationType: "Permanent",
    remarks: "Noise cancelling headphones for design work",
    status: "approved",
    acknowledgmentDate: "2023-06-16",
  },
  {
    id: "4",
    assetId: "16",
    employeeId: "EMP004",
    allocationDate: "2023-07-20",
    allocationType: "Permanent",
    remarks: "Gaming mouse for data visualization work",
    status: "approved",
    acknowledgmentDate: "2023-07-21",
  },
  {
    id: "5",
    assetId: "19",
    employeeId: "EMP005",
    allocationDate: "2023-08-10",
    allocationType: "Loan",
    remarks: "Temporary dock station for testing",
    status: "pending",
  },
]

export const mockEmployees: User[] = [
  {
    id: "2",
    name: "John Doe",
    email: "john@company.com",
    role: "employee",
    designation: "Software Engineer",
    department: "Engineering",
    profileImage: "/diverse-office-employee.png",
    employeeId: "EMP001",
  },
  {
    id: "3",
    name: "Jane Smith",
    email: "jane@company.com",
    role: "employee",
    designation: "Product Manager",
    department: "Product",
    profileImage: "/diverse-office-employee.png",
    employeeId: "EMP002",
  },
  {
    id: "4",
    name: "Robert Johnson",
    email: "robert@company.com",
    role: "employee",
    designation: "UX Designer",
    department: "Design",
    profileImage: "/diverse-office-employee.png",
    employeeId: "EMP003",
  },
  {
    id: "5",
    name: "Sarah Williams",
    email: "sarah@company.com",
    role: "employee",
    designation: "Data Analyst",
    department: "Analytics",
    profileImage: "/diverse-office-employee.png",
    employeeId: "EMP004",
  },
  {
    id: "6",
    name: "Michael Brown",
    email: "michael@company.com",
    role: "employee",
    designation: "DevOps Engineer",
    department: "Operations",
    profileImage: "/diverse-office-employee.png",
    employeeId: "EMP005",
  },
]